[package]
name = "tissue-rs"
version = "0.2.0"
authors = ["Yū Kobayashi <kb10uy@kb10uy.org>"]
edition = "2018"

# dependencies

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
chrono = { version = "0.4.19", features = ["serde"] }
async-trait = "0.1.51"
